'use strict'

const fs = require('fs')
const path = require('path')
const { findStale } = require('../utils/stale')

async function run(args) {
  if (!fs.existsSync('.docutrack')) {
    console.log('\nDocuTrack is not initialized. Run "npx docutrack init" first.\n')
    process.exit(1)
  }

  const root = process.cwd()
  const force = args.includes('--force')
  const outPath = path.join(root, 'docs', 'ONBOARDING.md')

  if (fs.existsSync(outPath) && !force) {
    console.log(`\nONBOARDING.md already exists. Use --force to regenerate.\n`)
    console.log(`  Location: ${outPath}\n`)
    return
  }

  console.log('\nDocuTrack — generating ONBOARDING.md\n')

  const sections = []

  // ── Project name + description ──────────────────────────
  const meta = getProjectMeta(root)
  sections.push(`# ${meta.name} — Onboarding Guide\n\n> Auto-generated by DocuTrack on ${new Date().toISOString().slice(0, 10)}.`)

  // ── What is this project? ───────────────────────────────
  const arch = readFile(root, 'ARCHITECTURE.md')
  if (arch) {
    // Extract intro paragraph (content before first ## header)
    const intro = arch.split(/^##\s/m)[0].replace(/^#[^\n]*\n/, '').trim()
    if (intro) {
      sections.push(`## What Is This?\n\n${intro}`)
    }
  }

  // ── Stack + framework ───────────────────────────────────
  const stackInfo = getStackInfo(root)
  if (stackInfo) sections.push(`## Stack\n\n${stackInfo}`)

  // ── Setup ───────────────────────────────────────────────
  const setup = getSetupInstructions(root, meta)
  sections.push(`## Getting Started\n\n${setup}`)

  // ── Module map ──────────────────────────────────────────
  const moduleDocs = loadModuleDocs(root)
  if (moduleDocs.length > 0) {
    const table = buildModuleTable(moduleDocs)
    sections.push(`## Module Map\n\n${table}`)
  }

  // ── API surface ─────────────────────────────────────────
  const apiInfo = getApiSummary(root)
  if (apiInfo) sections.push(`## API Surface\n\n${apiInfo}`)

  // ── Architecture highlights ─────────────────────────────
  if (arch) {
    const highlights = extractArchSection(arch, ['## Architecture', '## System Design', '## Design'])
    if (highlights) sections.push(`## Architecture Overview\n\n${highlights}`)
  }

  // ── ADRs ────────────────────────────────────────────────
  const adrs = loadAdrs(root)
  if (adrs.length > 0) {
    const adrList = adrs.map(a => `- **${a.title}** — ${a.status} · \`${a.file}\``).join('\n')
    sections.push(`## Key Decisions (ADRs)\n\n${adrList}\n\nRead the full ADRs in \`docs/decisions/\`.`)
  }

  // ── Documentation health ────────────────────────────────
  const healthSection = getHealthSummary(root)
  if (healthSection) sections.push(`## Documentation Health\n\n${healthSection}`)

  // ── Workflow ────────────────────────────────────────────
  sections.push(`## Development Workflow

1. Make your changes in a feature branch
2. Run \`docutrack status\` to see what needs documenting
3. Use the \`/arch-review\` slash command to check coverage
4. The documentalista subagent will update docs when the session ends
5. Run \`docutrack check\` to validate doc health before opening a PR

### Useful Commands

\`\`\`bash
docutrack status          # Coverage, pending files, stale docs
docutrack check           # Full health check: drift, complexity, stale
docutrack serve           # Open docs in browser at localhost:4242
docutrack analyze         # Re-scan API endpoints
docutrack badge           # Regenerate README badge
\`\`\`

### Slash Commands (in Claude Code)

| Command | Purpose |
|---------|---------|
| \`/doc-map\` | Visual map of all modules and endpoints |
| \`/arch-review\` | Coverage audit — which files lack docs |
| \`/adr-new\` | Guided ADR creation wizard |
| \`/ask-docs\` | Ask a question about the codebase using docs |
`)

  // ── Write output ────────────────────────────────────────
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, sections.join('\n\n---\n\n'))

  console.log(`  ✓ Generated: ${path.relative(root, outPath)}`)
  console.log(`  ${moduleDocs.length} modules documented`)
  if (adrs.length > 0) console.log(`  ${adrs.length} ADRs referenced`)
  console.log(`\nShare this with new contributors or serve it with "docutrack serve".\n`)
}

// ── Helpers ────────────────────────────────────────────────────────────────

function getProjectMeta(root) {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
    return { name: pkg.name || path.basename(root), version: pkg.version, description: pkg.description }
  } catch { /* ok */ }
  try {
    const mod = fs.readFileSync(path.join(root, 'go.mod'), 'utf8')
    const m = mod.match(/^module\s+(\S+)/m)
    return { name: m?.[1]?.split('/').pop() || path.basename(root), version: null }
  } catch { /* ok */ }
  return { name: path.basename(root), version: null }
}

function getStackInfo(root) {
  const lines = []
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
    const deps = { ...pkg.dependencies, ...pkg.devDependencies }
    const runtime = `Node.js ${pkg.engines?.node || '18+'}`
    lines.push(`| Runtime | ${runtime} |`)
    const fw = deps.next ? 'Next.js' : deps.express ? 'Express' : deps.fastify ? 'Fastify' : deps.koa ? 'Koa' : 'Node.js'
    lines.push(`| Framework | ${fw} |`)
    if (pkg.scripts) {
      const scripts = Object.entries(pkg.scripts).slice(0, 5).map(([k, v]) => `\`npm run ${k}\` — ${v}`).join('<br>')
      lines.push(`| Scripts | ${scripts} |`)
    }
  } catch { /* ok */ }
  try {
    const req = fs.readFileSync(path.join(root, 'requirements.txt'), 'utf8')
    if (req.toLowerCase().includes('fastapi')) {
      lines.push('| Runtime | Python 3.10+ |')
      lines.push('| Framework | FastAPI |')
    }
  } catch { /* ok */ }
  try {
    const mod = fs.readFileSync(path.join(root, 'go.mod'), 'utf8')
    const ver = mod.match(/^go\s+([\d.]+)/m)?.[1]
    if (ver) lines.push(`| Runtime | Go ${ver} |`)
  } catch { /* ok */ }

  if (!lines.length) return null
  return `| | |\n|---|---|\n${lines.join('\n')}`
}

function getSetupInstructions(root, meta) {
  const lines = []
  const hasPkg = fs.existsSync(path.join(root, 'package.json'))
  const hasPy = fs.existsSync(path.join(root, 'requirements.txt')) || fs.existsSync(path.join(root, 'pyproject.toml'))
  const hasGo = fs.existsSync(path.join(root, 'go.mod'))

  lines.push('```bash')
  lines.push('# Clone the repo')
  lines.push(`git clone <repo-url> && cd ${meta.name}`)

  if (hasPkg) {
    lines.push('')
    lines.push('# Install dependencies')
    const hasPnpm = fs.existsSync(path.join(root, 'pnpm-lock.yaml'))
    const hasYarn = fs.existsSync(path.join(root, 'yarn.lock'))
    lines.push(hasPnpm ? 'pnpm install' : hasYarn ? 'yarn install' : 'npm install')
  }
  if (hasPy) {
    lines.push('')
    lines.push('# Python setup')
    lines.push('python -m venv .venv && source .venv/bin/activate')
    lines.push(fs.existsSync(path.join(root, 'pyproject.toml')) ? 'pip install -e ".[dev]"' : 'pip install -r requirements.txt')
  }
  if (hasGo) {
    lines.push('')
    lines.push('go mod download')
  }

  lines.push('```')

  // Check for .env.example
  if (fs.existsSync(path.join(root, '.env.example'))) {
    lines.push('\n**Environment variables:**\n```bash\ncp .env.example .env\n# Edit .env with your values\n```')
  }

  return lines.join('\n')
}

function loadModuleDocs(root) {
  const docsDir = path.join(root, 'docs', 'modules')
  if (!fs.existsSync(docsDir)) return []
  const modules = []
  for (const file of fs.readdirSync(docsDir)) {
    if (!file.endsWith('.md')) continue
    const content = fs.readFileSync(path.join(docsDir, file), 'utf8')
    // Extract responsibility line
    const resp = content.match(/\*\*Responsibility\*\*:?\s*(.+)/)?.[1]?.trim()
      || content.match(/^##?\s*Responsibility\s*\n+(.+)/m)?.[1]?.trim()
      || content.split('\n').filter(l => l.trim() && !l.startsWith('#'))[0]?.slice(0, 100)
    modules.push({ name: file.replace('.md', ''), responsibility: resp || '—', file: `docs/modules/${file}` })
  }
  return modules
}

function buildModuleTable(modules) {
  const rows = modules.map(m => `| \`${m.name}\` | ${m.responsibility} |`)
  return `| Module | Responsibility |\n|--------|----------------|\n${rows.join('\n')}`
}

function getApiSummary(root) {
  const specPath = path.join(root, 'docs', 'api', 'openapi.json')
  if (!fs.existsSync(specPath)) return null
  try {
    const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'))
    const pathCount = Object.keys(spec.paths || {}).length
    if (pathCount === 0) return null
    const methods = {}
    for (const p of Object.values(spec.paths)) {
      for (const m of Object.keys(p)) methods[m] = (methods[m] || 0) + 1
    }
    const summary = Object.entries(methods).map(([m, n]) => `${n} ${m.toUpperCase()}`).join(', ')
    const tags = [...new Set(Object.values(spec.paths).flatMap(p => Object.values(p).flatMap(op => op.tags || [])))]
    return `**${pathCount} endpoints** (${summary})\\\nGroups: ${tags.map(t => `\`${t}\``).join(', ')}\n\nRun \`docutrack serve\` and open **API Explorer** to try endpoints interactively.`
  } catch { return null }
}

function extractArchSection(content, headerNames) {
  for (const header of headerNames) {
    const re = new RegExp(`${header.replace('## ', '^## ')}[\\s\\S]*?(?=^## |$)`, 'm')
    const match = content.match(re)
    if (match) return match[0].replace(/^## [^\n]*\n/, '').trim().slice(0, 800)
  }
  return null
}

function loadAdrs(root) {
  const dir = path.join(root, 'docs', 'decisions')
  if (!fs.existsSync(dir)) return []
  const adrs = []
  for (const file of fs.readdirSync(dir)) {
    if (!file.endsWith('.md') || file === '.gitkeep') continue
    const content = fs.readFileSync(path.join(dir, file), 'utf8')
    const title = content.match(/^#\s+(.+)/m)?.[1] || file.replace('.md', '')
    const status = content.match(/##?\s*Status\s*:?\s*(.+)/i)?.[1]?.trim() || 'Unknown'
    adrs.push({ file: `docs/decisions/${file}`, title, status })
  }
  return adrs.slice(0, 10)
}

function getHealthSummary(root) {
  try {
    const queue = JSON.parse(fs.readFileSync(path.join(root, '.docutrack', 'queue.json'), 'utf8'))
    const stale = findStale(root)
    const docCount = countDocs(root)
    const pending = queue.pending?.length || 0
    const lines = [
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Documented modules | ${docCount} |`,
      `| Pending queue | ${pending} files |`,
      `| Stale docs | ${stale.length} |`,
    ]
    return lines.join('\n')
  } catch { return null }
}

function countDocs(root) {
  const d = path.join(root, 'docs', 'modules')
  if (!fs.existsSync(d)) return 0
  return fs.readdirSync(d).filter(f => f.endsWith('.md')).length
}

function readFile(root, file) {
  try { return fs.readFileSync(path.join(root, file), 'utf8') } catch { return null }
}

module.exports = { run }
